// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM1PULqZhfR0UZ8SitTntIeiBOwBpJsmI',
    appId: '1:49519904995:web:2cd7bc2df641f600679dd6',
    messagingSenderId: '49519904995',
    projectId: 'chat-me-1e6bb',
    authDomain: 'chat-me-1e6bb.firebaseapp.com',
    storageBucket: 'chat-me-1e6bb.appspot.com',
    measurementId: 'G-2R73W9MKBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wamBelt4hjSMhmL0Gfnj9t8dax4DvTA',
    appId: '1:49519904995:android:b0ac7fd08206e932679dd6',
    messagingSenderId: '49519904995',
    projectId: 'chat-me-1e6bb',
    storageBucket: 'chat-me-1e6bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi-RbVhVZGm6Jq8CiOum1zlIbJhl_E8-0',
    appId: '1:49519904995:ios:6a40051a5a5a25c3679dd6',
    messagingSenderId: '49519904995',
    projectId: 'chat-me-1e6bb',
    storageBucket: 'chat-me-1e6bb.appspot.com',
    iosBundleId: 'com.chatme.chatMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi-RbVhVZGm6Jq8CiOum1zlIbJhl_E8-0',
    appId: '1:49519904995:ios:6a40051a5a5a25c3679dd6',
    messagingSenderId: '49519904995',
    projectId: 'chat-me-1e6bb',
    storageBucket: 'chat-me-1e6bb.appspot.com',
    iosBundleId: 'com.chatme.chatMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM1PULqZhfR0UZ8SitTntIeiBOwBpJsmI',
    appId: '1:49519904995:web:8b9df2ac4d9dbf05679dd6',
    messagingSenderId: '49519904995',
    projectId: 'chat-me-1e6bb',
    authDomain: 'chat-me-1e6bb.firebaseapp.com',
    storageBucket: 'chat-me-1e6bb.appspot.com',
    measurementId: 'G-EWBXVKKB0L',
  );
}
